import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className='min-h-screen min-w-screen'>
        
        <nav className='h-16 bg-gray-800 text-white flex justify-between items-center px-4'>
          <div>
            <p>Firs Project</p>
          </div>
          <ul className='flex justify-center items-center space-x-4'> 
         <li>second</li>
         <li>second</li>
         <li>second</li>
         <li>second</li>
         <li>second</li>
          </ul>

        </nav>
      <div>
      {children}
        </div>  
        </body>
    </html>
  )
}
